### PR TITLE
Fix #103: Dealing with un-escaped environment variables by using `args`

### LINKED ISSUE #103: Exported environment variables w/quotes break the docker run command
Let's start with my branch of Azure/cli here as the diff from source shows how I enabled logging of the `docker run` command to find the issue: https://github.com/MT-Jacobs/azure-cli

The file I edited is in `src/main.ts`.

Anyhow - 

If you run Azure CLI commands, you might choose to pass along an environment variable to the `docker run` command like so:

```
docker run ...
-e "COMMIT_MESSAGE=Message here"
...
mcr.microsoft.com/azure-cli:2.48.1  bash --noprofile --norc
...
``` 

However, if the variable has quotes in it - like can often happen if you, say, supplied a commit message for a revert in Github - you get the following:

```
docker run ...
-e "COMMIT_MESSAGE=Revert "Original commit message" (#882)"
...
mcr.microsoft.com/azure-cli:2.48.1  bash --noprofile --norc
...
```

these un-escaped quotes break parsing of the `docker run` command and results in a misleading message:

```
Error: Error: docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

Environment variables need to be properly escaped. The issue is in this area of the script, I believe:

```ts
        let environmentVariables = '';
        for (let key in process.env) {
            // if (key.toUpperCase().startsWith("GITHUB_") && key.toUpperCase() !== 'GITHUB_WORKSPACE' && process.env[key]){
            if (!checkIfEnvironmentVariableIsOmitted(key) && process.env[key]) {
                environmentVariables += ` -e "${key}=${process.env[key]}" `;
            }
        }
```

### PR DESCRIPTION
**Pull request by MoChilia**
### Description

This PR is going to fix #103. We utilize the built-in function in [`@actions/exec.exec`](https://www.npmjs.com/package/@actions/exec?activeTab=readme) to escape for the incoming arguments. 

Refer to [this instruction](https://github.com/actions/toolkit/blob/a6bf8726aa7b78d4fc8111359cca5d538527b239/packages/exec/src/exec.ts#L13), we can implement automatic escape for incoming arguments by using the parameter `args` of function `@actions/exec.exec`.
```
 * @param     args               optional arguments for tool. Escaping is handled by the lib.
```
The reason why only escaping double quotes may not be sufficient was discussed in https://github.com/Azure/cli/pull/104#discussion_r1213961750.

### Test workflows
[Test Azure CLI for escaping in env](https://github.com/MoChilia/ActionsDemo/actions/runs/5154830970/jobs/9316911437)

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -65,15 +57,26 @@ export async function main(){
...
-        command += ` mcr.microsoft.com/azure-cli:${azcliversion} ${startCommand}`;
+        let command: string = `run`;
+        var args = ["--workdir", `${process.env.GITHUB_WORKSPACE}`,
+            "-v", `${process.env.GITHUB_WORKSPACE}:${process.env.GITHUB_WORKSPACE}`,
+            "-v", `${process.env.HOME}/.azure:/root/.azure`,
+            "-v", `${TEMP_DIRECTORY}:${TEMP_DIRECTORY}`
+        ];
+        for (let key in process.env) {
+            if (!checkIfEnvironmentVariableIsOmitted(key) && process.env[key]) {
+                args = args.concat("-e", `${key}=${process.env[key]}`);
```
Comment (jiasli) [inline src/main.ts:68]: [`concat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat) creates a new array every time. We may consider using [`push`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push).

File: src/main.ts [hunk 2]
```diff
@@ -65,15 +57,26 @@ export async function main(){
...
+            }
+        }
+        args = args.concat("--name", `${CONTAINER_NAME}`,
+            `mcr.microsoft.com/azure-cli:${azcliversion}`,
+            `bash`, `--noprofile`, `--norc`, `-e`, `${TEMP_DIRECTORY}/${scriptFileName}`);
```
Comment (jiasli) [inline src/main.ts:73]: [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) is not needed for plain text string.

File: src/main.ts [hunk 3]
```diff
@@ -115,7 +118,7 @@ const getAllAzCliVersions = async (): Promise<Array<string>> => {
     return [];
 }
 
-const executeDockerCommand = async (dockerCommand: string, continueOnError: boolean = false): Promise<void> => {
+const executeDockerCommand = async (dockerCommand: string, args: any = [], continueOnError: boolean = false): Promise<void> => {
```
Comment (jiasli) [inline src/main.ts:121]: We may make the type of `args` more explicit, such as `string[]`. https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#arrays

File: src/main.ts [hunk 4]
```diff
@@ -140,7 +142,7 @@ const executeDockerCommand = async (dockerCommand: string, continueOnError: bool
     };
     var exitCode;
     try {
-        exitCode = await exec.exec(`"${dockerTool}" ${dockerCommand}`, [], execOptions);
+        exitCode = await exec.exec(`"${dockerTool}" ${dockerCommand}`, args, execOptions);
```
Comment (jiasli) [inline src/main.ts:145]: (At least for Python `subprocess` module) The convention is to only use `commandLine` to specify the docker tool's path `${dockerTool}`. `${dockerCommand}` such as `run` should be included in `args`. Even though they are docker's commands, on Shell level, they are command's arguments.

https://docs.python.org/3/library/subprocess.html#subprocess.Popen

> On POSIX, if args is a string, the string is interpreted as the name or path of the program to execute. However, this can only be done if not passing arguments to the program.

File: src/main.ts [hunk 5]
```diff
@@ -8,11 +8,10 @@ const cpExec = util.promisify(require('child_process').exec);
 
 import { createScriptFile, TEMP_DIRECTORY, NullOutstreamStringWritable, deleteFile, getCurrentTime, checkIfEnvironmentVariableIsOmitted } from './utils';
 
-const START_SCRIPT_EXECUTION_MARKER: string = `Starting script execution via docker image mcr.microsoft.com/azure-cli:`;
-const BASH_ARG: string = `bash --noprofile --norc -e `;
+const START_SCRIPT_EXECUTION_MARKER: string = "Starting script execution via docker image mcr.microsoft.com/azure-cli:";
 const AZ_CLI_VERSION_DEFAULT_VALUE = 'agentazcliversion'
 
-export async function main(){
+export async function main() {
```
Comment (jiasli) [inline src/main.ts:14]: Is there any linter tool for TypeScript? A linter can help us normalize the code style and avoid distracting diffs like this. 

Just a reminder. No need to do that right now.

**Comment by jiasli** [comment]
Glad to see we are taking security as our top priority and trying our best to avoid possible security risks. Nice work!

**Review by jiasli — APPROVED** [review]
